spring:
  application:
    name: dubbo-provider
dubbo:
  protocol:
    name: dubbo
    port: 2333
  registry:
    address: zookeeper://zk:2181 #zk docker-composeä¸­service
logging:
  file:
    name: /tmp/provider.log


